/*
  Warnings:

  - The values [VIBRATING_COUPLES,REMOTE_COUPLES,DUAL_COUPLES] on the enum `ProductTag` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ProductTag_new" AS ENUM ('FIRST_TOY_WOMEN', 'INACTIVE_USER_WOMEN', 'PROFI_LEVEL_WOMEN', 'TOY_WOMEN', 'APP_WOMEN', 'REMOTE_CONTROL_WOMEN', 'LIGHT_MODE_WOMEN', 'MEDIUM_POWER_WOMEN', 'HIGH_INTENSITY_WOMEN', 'CLITORS_WOMEN', 'ANAL_WOMEN', 'VAGINA_WOMEN', 'VACUUM_WOMEN', 'VIBRO_WOMEN', 'MOTION_WOMEN', 'FIRST_TOY_MEN', 'INACTIVE_USER_MEN', 'PROFI_LEVEL_MEN', 'TOY_MEN', 'APP_MEN', 'REMOTE_CONTROL_MEN', 'LIGHT_MODE_MEN', 'MEDIUM_POWER_MEN', 'HIGH_INTENSITY_MEN', 'DICK_MEN', 'PENIS_HEAD_MEN', 'BALLS_MEN', 'ANAL_MEN', 'MASTURBATOR_MEN', 'CONTINUATION_MEN', 'VIBRO_MEN', 'PROFI_LEVEL_COUPLE', 'INACTIVE_USER_COUPLE', 'FIRST_TOY_COUPLE', 'HE_COUPLE', 'SHE_COUPLE', 'THEM_COUPLE', 'LIGHT_MODE_COUPLE', 'MEDIUM_POWER_COUPLE', 'HIGH_INTENSITY_COUPLE', 'TOYS_COUPLE', 'PETTING_COUPLE', 'BDSM_COUPLE', 'HOME_COUPLE', 'DISTANCE_COUPLE', 'WALK_COUPLE');
ALTER TABLE "TagArr" ALTER COLUMN "tag" TYPE "ProductTag_new" USING ("tag"::text::"ProductTag_new");
ALTER TYPE "ProductTag" RENAME TO "ProductTag_old";
ALTER TYPE "ProductTag_new" RENAME TO "ProductTag";
DROP TYPE "public"."ProductTag_old";
COMMIT;

-- DropIndex
DROP INDEX "TagItems_tagName_key";
