-- CreateEnum
CREATE TYPE "TagGenderType" AS ENUM ('UNDEFINED', 'COUPLE', 'MEN', 'WOMEN');

-- CreateEnum
CREATE TYPE "ProductTag" AS ENUM ('FIRST_TOY_WOMEN', 'INACTIVE_USER_WOMEN', 'PROFI_LEVEL_WOMEN', 'TOY_WOMEN', 'APP_WOMEN', 'REMOTE_CONTROL_WOMEN', 'LIGHT_MODE_WOMEN', 'MEDIUM_POWER_WOMEN', 'HIGH_INTENSITY_WOMEN', 'CLITORS_WOMEN', 'ANAL_WOMEN', 'VAGINA_WOMEN', 'VACUUM_WOMEN', 'VIBRO_WOMEN', 'MOTION_WOMEN', 'FIRST_TOY_MEN', 'INACTIVE_USER_MEN', 'PROFI_LEVEL_MEN', 'TOY_MEN', 'APP_MEN', 'REMOTE_CONTROL_MEN', 'LIGHT_MODE_MEN', 'MEDIUM_POWER_MEN', 'HIGH_INTENSITY_MEN', 'DICK_MEN', 'PENIS_HEAD_MEN', 'BALLS_MEN', 'ANAL_MEN', 'MASTURBATOR_MEN', 'CONTINUATION_MEN', 'VIBRO_MEN', 'PROFI_LEVEL_COUPLE', 'INACTIVE_USER_COUPLE', 'FIRST_TOY_COUPLE', 'HE_COUPLE', 'SHE_COUPLE', 'THEM_COUPLE', 'LIGHT_MODE_COUPLE', 'MEDIUM_POWER_COUPLE', 'HIGH_INTENSITY_COUPLE', 'TOYS_COUPLE', 'PETTING_COUPLE', 'BDSM_COUPLE', 'HOME_COUPLE', 'DISTANCE_COUPLE', 'WALK_COUPLE', 'VIBRATING_COUPLES', 'REMOTE_COUPLES', 'DUAL_COUPLES');

-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "tagGender" "TagGenderType" NOT NULL DEFAULT 'UNDEFINED';

-- CreateTable
CREATE TABLE "TagAnswers" (
    "id" SERIAL NOT NULL,
    "question" TEXT NOT NULL DEFAULT '-',
    "isMultiply" BOOLEAN NOT NULL DEFAULT false,
    "productId" INTEGER,

    CONSTRAINT "TagAnswers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AnswersArr" (
    "id" SERIAL NOT NULL,
    "answer" TEXT NOT NULL DEFAULT '-',
    "tagAnswersId" INTEGER,

    CONSTRAINT "AnswersArr_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TagArr" (
    "id" SERIAL NOT NULL,
    "tag" "ProductTag" NOT NULL,
    "tagAnswersId" INTEGER,

    CONSTRAINT "TagArr_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "TagAnswers" ADD CONSTRAINT "TagAnswers_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AnswersArr" ADD CONSTRAINT "AnswersArr_tagAnswersId_fkey" FOREIGN KEY ("tagAnswersId") REFERENCES "TagAnswers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TagArr" ADD CONSTRAINT "TagArr_tagAnswersId_fkey" FOREIGN KEY ("tagAnswersId") REFERENCES "TagAnswers"("id") ON DELETE CASCADE ON UPDATE CASCADE;
